//Fonts
import { roboto, fira } from '@font/font';

//Styles
import '@styles/globals.css';
import '@styles/normalize.css';

//Types
import type { Metadata } from 'next';

//const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={`${roboto.variable} ${fira.variable}`}>{children}</body>
    </html>
  );
}
